language: python
branches:
  except:
  - gh-pages
cache:
  directories:
  - "${HOME}/.pip"
python:
- 3.7
- 3.6
- 3.5
matrix:
  fast_finish: true
install:
- pip install tox
- pip install tox-travis
script:
- tox
after_success:
- pylint steenzout
- pip install coveralls
- coveralls
deploy:
  provider: pypi
  user: '__token__'
  password:
    secure: yxJdpCj4WhxdDbN+r7md+clBusLcwQ41jqwPy87lHKLGEHsjXSaNPHf2HCQiOaEAN7E8/ZO0qzG7OqVL8+MqSgO1qZN5WukAv4gXTQq+qMO+A45NwdiHdK/ldpObNRB1FbAGGJYCJS/1gfOH3+Q9WyT5h6E+Gi4dtlD7mAVjXmq73KBFxlLIteIH3S2L28CCO4wjuRWogNtueRBGtWkcFzTPi0HhvSR4gZXBEZh9l4uX3pL+GrGqqSfInHb9z70swczX1x6bfdYayLngHuGc8V8xwUEQW9YDZzXh1oJ0JUjxXsfdvZbh3eGHzKxGpmalBZNA5/NnY75PLCT7Iq8qRvPJTAGuAxJ9pFI/YwN0BiJU/QpY34N7+n6dkNfN0w2VFBlZLSYW+zuAfdnAGOJcqft1pLTahfm9EfJEq5mSdma7pdQI8e4PJHrqf5jX76VtxHGcgAt+MMjfeDgLdxoc3aYV3HkyrPrptMCN2NYAuTiSzKuxwZlr5Enriz4SGRp3t0qQMPDrwiWskPN1yiI/MOXipf+5ECwMb0zXoW3eTgsNALOI184WQvkfOewA8kvdGl7AXWOHNMoP8Us1UiwPlQt9WcTFLuYZB1Rlo/dFtGsHxcrmGlDsskokUUMFepnpr5Fh8lELo0P7zf+DzKhHFHedsX/2Dy9NlJPbAcgYBKg=
  on:
    tags: true
