language: python

branches:
  except:
    - gh-pages

cache:
  directories:
    - "${HOME}/.pip"

python:
  - 3.6
  - 3.5
  - 2.7


matrix:
  fast_finish: true
  allow_failures:
    - python: 3.6

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

after_success:
  - pylint steenzout
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: steenzout
  password:
    secure: "y6Ug8GGsPVwaG6ePN6tGK5RVKdoNJAt7BXaGFQDEoVHgkTQ91Zd9NGU6cebAcAkaMfgRwLv0NzZcVptr8Ot/2oCa8yG9NWm1/057sIck4YsvSMiCl7mlQN4h2Bg0Uh4NXBb32sgecXr/hWBcnz9luyYEjJ3itMWoJKHUUhfgyM4ij9/RdLkOOYdCxu2Ce79Oc/NpAkqFZIGXHj/6knAFAwbRRDejEBf8I+tCJLpWYvOKLmSnTmH7ili9MjJGLHMDlNeQm3sRkrcmyaZw+3KnkQNvURfHPXRttqi3mSv7s7CszNfWBJigE4QDxYqsm1ln8767xZMKa4I2vrFOPAIefiLoXIFQP9uzHC3jP5pUhDAflKzzv9VVXMV48y01jOZ0j3/c2R8p7VSey3cx+RYavqdD2KvFkhuPnRevsvSjnJDTZVVO3cIo17DmYS6iAiqcou0GQ2YzG0m+LLEvQ1alqTNMtwdTXOlEZKSA6iysMSmleDLZVDZemZMFTMtQlMGvAUrQdDRnYPm87Vvy7bnzauDNS+HGffDcn80ziiZxmhmpJxZwDlHupzDlbcULeZGcj/u0X6QZhgjBq/x4KUqNwZEl2JtjQ2X6CawromI99DNukoNz8NBIF/+0+ycOmNVDtsBwtIH99Qwg4TzN2bqImdrycWAnVQ2aiOmarEUYYnY="
  on:
    tags: true
