language: python

branches:
  except:
    - gh-pages

cache:
  directories:
    - "${HOME}/.pip"

python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7


matrix:
  fast_finish: true
  allow_failures:
    - python: 3.7

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

after_success:
  - pylint steenzout
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  user: steenzout
  password:
    secure: "XvyOTcXH2R/Sb402O2PMHygwladhSvyTxPr9vyiFY6twdjpXE1XfKlJv3qOQ7UY3cJmmASczA/spRwQOWpaV5LA2lNhUiUYinQ+eFWtP7vsm4xViZyQgwfrSKm6ZERvfiq/BWCaQ/RgYnfWMtxyVVsuIfzigngb26rAvgU0QpCVKtPYhentCBZvasSug5lZPLrvHG67QxPZqRBU0IcyzipJR0LX9T+5bgfEiPnAgl0I40+BQUrddtXZw75aRUcNVwPi7lBe0Gi51PFjBM9ixpXQQMpcYEMJvURLoX+uyXxm1v+Hgif85R1AjnhNvzIGeK4LGYeQLshYL5wUJofIxVhFKVUSRxhK2EOLYUbjeWpYHCHD3bpC/TxRjja4712XpmqdGAPaKmCYSikWlIWv6gJiwl3hszOLqMZhNmlew+xx/Q5EyhOBFZeikrHIaXPDbef9kJoo4P/2U4SlUO8Hu8o+yLDgmnd5F9VnCMTrC0XMCAZKOtDmpz9rWzSpQEmUqNLpcWgxd574JLn6LLgxIpaYQT0fYLCgLHcAjBfaSbwL6uEtDGhlZGomMQHS/4cntfnZGhJAp+z//hgWbcqZhZoPgNBOmrZcrcWgeh97a4TClVLT6FG4JKAiRV2F8QMz8u8hcFJJB29lnxyxui2nut787SNBnxlwDHg7Oze3bnzo="
  on:
    tags: true
