# -*- coding: utf-8 -*-
"""Package to standardize Sphinx documentation in a GitHub organization."""

import sys

import semantic_version

from recommonmark.parser import CommonMarkParser


def register(metadata):
    """Register Sphinx configuration for the given package into the conf module.

    Args:
        metadata (:py:module): module that contains the metadata information.
    """

    # retrieve the conf.py module from which this function was called
    conf_module = sys.modules['__builtin__']
    package = metadata.__name__[:metadata.__name__.rindex('.')]

    #
    # Sphinx documentation build configuration file.
    #
    # All configuration values have a default;
    # values that are commented out serve to show the default.

    # If extensions (or modules to document with autodoc) are in another directory,
    # add these directories to sys.path here.
    # If the directory is relative to the documentation root,
    # use os.path.abspath to make it absolute, like shown here.
    #

    _version = semantic_version.Version(metadata.__version__)

    # -- General configuration ------------------------------------------------

    # If your documentation needs a minimal Sphinx version, state it here.
    #
    # needs_sphinx = '1.0'

    # Add any Sphinx extension module names here, as strings. They can be
    # extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
    # ones.
    conf_module.extensions = [
        'sphinx.ext.autodoc',
        'sphinx.ext.coverage',
        'sphinx.ext.imgmath',
        'sphinx.ext.napoleon',
        'sphinx.ext.viewcode',
    ]

    # Add any paths that contain templates here, relative to this directory.
    conf_module.templates_path = ['_templates']

    # The suffix(es) of source filenames.
    # You can specify multiple suffix as a list of string:
    #
    # conf_module.source_suffix = '.rst'
    conf_module.CommonMarkParser = CommonMarkParser
    conf_module.source_parsers = {
        '.md': conf_module.CommonMarkParser
    }
    conf_module.source_suffix = [
        '.md',
        '.rst'
    ]

    # The encoding of source files.
    #
    # conf_module.source_encoding = 'utf-8-sig'

    # The master toctree document.
    conf_module.master_doc = 'index'

    # General information about the project.
    conf_module.project = package
    conf_module.author = metadata.__author__
    conf_module.copyright = metadata.__copyright__

    # The version info for the project you're documenting, acts as replacement for
    # |version| and |release|, also used in various other places throughout the
    # built documents.
    #
    # The short X.Y version.
    conf_module.version = u'%d.%d' % (_version.major, _version.minor)
    # The full version, including alpha/beta/rc tags.
    conf_module.release = _version

    # The language for content autogenerated by Sphinx. Refer to documentation
    # for a list of supported languages.
    #
    # This is also used if you do content translation via gettext catalogs.
    # Usually you set "language" from the command line for these cases.
    conf_module.language = 'en'

    # There are two options for replacing |today|: either, you set today to some
    # non-false value, then it is used:
    #
    # today = ''
    #
    # Else, today_fmt is used as the format for a strftime call.
    #
    # today_fmt = '%B %d, %Y'

    # List of patterns, relative to source directory, that match files and
    # directories to ignore when looking for source files.
    # This patterns also effect to html_static_path and html_extra_path
    conf_module.exclude_patterns = ['_build', '_templates', 'Thumbs.db', '.DS_Store']

    # The reST default role (used for this markup: `text`) to use for all
    # documents.
    #
    # conf_module.default_role = None

    # If true, '()' will be appended to :func: etc. cross-reference text.
    #
    # conf_module.add_function_parentheses = True

    # If true, the current module name will be prepended to all description
    # unit titles (such as .. function::).
    #
    conf_module.add_module_names = False

    # If true, sectionauthor and moduleauthor directives will be shown in the
    # output. They are ignored by default.
    #
    # conf_module.show_authors = False

    # The name of the Pygments (syntax highlighting) style to use.
    conf_module.pygments_style = 'sphinx'

    # A list of ignored prefixes for module index sorting.
    # conf_module.modindex_common_prefix = []

    # If true, keep warnings as "system message" paragraphs in the built documents.
    # conf_module.keep_warnings = False

    # If true, `todo` and `todoList` produce output, else they produce nothing.
    conf_module.todo_include_todos = False


    # -- Options for HTML output ----------------------------------------------

    # The theme to use for HTML and HTML Help pages.  See the documentation for
    # a list of builtin themes.
    #
    conf_module.html_theme = 'sphinx_rtd_theme'

    # Theme options are theme-specific and customize the look and feel of a theme
    # further.  For a list of options available for each theme, see the
    # documentation.
    #
    conf_module.html_theme_options = {
    }

    # Add any paths that contain custom themes here, relative to this directory.
    # conf_module.html_theme_path = []

    # The name for this set of Sphinx documents.
    # "<project> v<release> documentation" by default.
    #
    # conf_module.html_title = u''

    # A shorter title for the navigation bar.  Default is the same as html_title.
    #
    # conf_module.html_short_title = None

    # The name of an image file (relative to this directory) to place at the top
    # of the sidebar.
    #
    # conf_module.html_logo = None

    # The name of an image file (relative to this directory) to use as a favicon of
    # the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
    # pixels large.
    #
    # conf_module.html_favicon = None

    # Add any paths that contain custom static files (such as style sheets) here,
    # relative to this directory. They are copied after the builtin static files,
    # so a file named "default.css" will overwrite the builtin "default.css".
    conf_module.html_static_path = ['_static']

    # Add any extra paths that contain custom files (such as robots.txt or
    # .htaccess) here, relative to this directory. These files are copied
    # directly to the root of the documentation.
    #
    # conf_module.html_extra_path = []

    # If not None, a 'Last updated on:' timestamp is inserted at every page
    # bottom, using the given strftime format.
    # The empty string is equivalent to '%b %d, %Y'.
    #
    # conf_module.html_last_updated_fmt = None

    # If true, SmartyPants will be used to convert quotes and dashes to
    # typographically correct entities.
    #
    # conf_module.html_use_smartypants = True

    # Custom sidebar templates, maps document names to template names.
    #
    # conf_module.html_sidebars = {}

    # Additional templates that should be rendered to pages, maps page names to
    # template names.
    #
    # conf_module.html_additional_pages = {}

    # If false, no module index is generated.
    #
    # conf_module.html_domain_indices = True

    # If false, no index is generated.
    #
    # conf_module.html_use_index = True

    # If true, the index is split into individual pages for each letter.
    #
    # conf_module.html_split_index = False

    # If true, links to the reST sources are added to the pages.
    #
    conf_module.html_show_sourcelink = False

    # If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
    #
    # conf_module.html_show_sphinx = True

    # If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
    #
    # conf_module.html_show_copyright = True

    # If true, an OpenSearch description file will be output, and all pages will
    # contain a <link> tag referring to it.  The value of this option must be the
    # base URL from which the finished HTML is served.
    #
    # conf_module.html_use_opensearch = ''

    # This is the file name suffix for HTML files (e.g. ".xhtml").
    # conf_module.html_file_suffix = None

    # Language to be used for generating the HTML full-text search index.
    # Sphinx supports the following languages:
    #   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
    #   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
    #
    # conf_module.html_search_language = 'en'

    # A dictionary with options for the search language support, empty by default.
    # 'ja' uses this config value.
    # 'zh' user can custom change `jieba` dictionary path.
    #
    # conf_module.html_search_options = {'type': 'default'}

    # The name of a javascript file (relative to the configuration directory) that
    # implements a search results scorer. If empty, the default will be used.
    #
    # conf_module.html_search_scorer = 'scorer.js'

    # Output file base name for HTML help builder.
    conf_module.htmlhelp_basename = u'py_%s' % package.replace('.', '_')

    # -- Options for LaTeX output ---------------------------------------------

    conf_module.latex_elements = {
         # The paper size ('letterpaper' or 'a4paper').
         #
         # 'papersize': 'letterpaper',

         # The font size ('10pt', '11pt' or '12pt').
         #
         # 'pointsize': '10pt',

         # Additional stuff for the LaTeX preamble.
         #
         # 'preamble': '',

         # Latex figure (float) alignment
         #
         # 'figure_align': 'htbp',
    }

    # Grouping the document tree into LaTeX files.
    # List of tuples (
    #   source start file,
    #   target name,
    #   title,
    #   author,
    #   documentclass [howto, manual, or own class]
    # ).
    conf_module.latex_documents = [(
        conf_module.master_doc,
        u'py_%s.tex' % package.replace('.', '_'),
        u'%s documentation' % package,
        metadata.__author__,
        u'manual'
    )]

    # The name of an image file (relative to this directory) to place at the top of
    # the title page.
    #
    # conf_module.latex_logo = None

    # For "manual" documents, if this is true, then toplevel headings are parts,
    # not chapters.
    #
    # conf_module.latex_use_parts = False

    # If true, show page references after internal links.
    #
    # conf_module.latex_show_pagerefs = False

    # If true, show URL addresses after external links.
    #
    # conf_module.latex_show_urls = False

    # Documents to append as an appendix to all manuals.
    #
    # conf_module.latex_appendices = []

    # It false, will not define \strong, \code, 	itleref, \crossref ... but only
    # \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
    # sphinxs.
    #
    # conf_module.latex_keep_old_macro_names = True

    # If false, no module index is generated.
    #
    # conf_module.latex_domain_indices = True


    # -- Options for manual page output ---------------------------------------

    # One entry per manual page.
    # List of tuples (
    #   source start file,
    #   name,
    #   description,
    #   authors,
    #   manual section
    # ).
    conf_module.man_pages = [(
        conf_module.master_doc,
        'py_%s' % package.replace('.', '_'),
        '%s documentation' % package,
        [metadata.__author__],
        1
    )]

    # If true, show URL addresses after external links.
    #
    # man_show_urls = False


    # -- Options for Texinfo output -------------------------------------------

    # Grouping the document tree into Texinfo files.
    # List of tuples (
    #   source start file,
    #   target name,
    #   title,
    #   author,
    #   dir menu entry,
    #   description,
    #   category
    # ).
    conf_module.texinfo_documents = [(
        conf_module.master_doc,
        u'py_%s' % package.replace('.', '_'),
        u'%s documentation' % package,
        metadata.__author__,
        u'',
        u'%s documentation.' % package,
        u'Miscellaneous'
    )]

    # Documents to append as an appendix to all manuals.
    #
    # conf_module.texinfo_appendices = []

    # If false, no module index is generated.
    #
    # conf_module.texinfo_domain_indices = True

    # How to display URL addresses: 'footnote', 'no', or 'inline'.
    #
    # conf_module.texinfo_show_urls = 'footnote'

    # If true, do not generate a @detailmenu in the "Top" node's menu.
    #
    # conf_module.texinfo_no_detailmenu = False
